config/routes.rb
Smartsalon::Application.routes.draw do

  get "client_services/index"

  get "client_services/new"

  get "dashboard/index"

  get "dashboard" => "dashboard#index"

  post "favorites" => "favorites#create"

  delete "favorites/:id" => "favorites#destroy"

  resources :settings

  namespace :landing do
    root :to => "pages#index"
    get "pages/index"
    get "pages/about"
  end

  namespace :admin do    
    root :to => "dashboard#index"
    post "payments/notification" => "payments#notification", :as => "payment_notification"
    get 'dashboard' => "dashboard#index"
    
    resources :services do
      collection do
        get 'get_services'
        get 'search'
      end
      resources :client_services
    end      
    
    resources :events do      
      collection do
        get "easy/new" => "events#easy_new"
        post "easy/new" => "events#easy_create"
        get 'get_events'
        get 'search'
        get 'calendar'
      end
      member do
        post "edit" => "events#update"
      end
    end
    
    resources :professionals do
      collection do
        post "search_zipcode" => "professionals#search_zipcode"
      end
      put "update_password" => "professionals#update_password", :as => "update_password", :on => :member
      resources :working_times
      resources :professional_services
    end
    
    resources :salons do
      collection do
        post "search_zipcode" => "salons#search_zipcode"
      end
      post "payments/checkout" => "payments#checkout", :as => "payments_checkout"
      get "payments/:payment_id/receipt" => "payments#receipt", :as => "payments_receipt"
    end
    
    resources :clients do
      post "add/to/salon" => "clients#add_to_salon", :as => "add_to_salon"
      collection do
        get "search"
      end
      resources :client_services      
    end
    
    resources :client_services
  end

  devise_for :clients, :controllers =>
  {
    :registrations => "registrations"
  }

  devise_for :users, :controllers => 
  { 
    :registrations => "registrations" ,
    :sessions => "sessions"
  }

  devise_for :professionals, 
  :controllers => 
  { 
    :registrations => "registrations" ,
    :sessions => "admin/sessions"
  }

  resources :clients do
    resources :events
  end

  resources :salons do
    get 'page/:page', :action => :index, :on => :collection
    post "events/:id/edit" => "events#update"
    post "events/new" => "events#create"
    resources :events
  end

  resources :events

  resources :users

  root :to => "dashboard#index"

end

app/models/client.rb
class Client < User
  has_many :events
  has_many :client_salons  
  has_many :salons, :through => :client_salons
  has_many :favorites
  has_many :client_services
  has_many :services, :through => :client_services
  validates :name,:celphone, :presence => true
  validates :celphone, :email, :uniqueness => true  
  after_create :send_email_notice

  def my_salons_and_favorites
  	self.favorites.map(&:salon) | self.salons
  end

  def associated_services
    self.client_services.joins(:salon)
  end

  def send_email_notice  	
  	if self.created_by
  		@salon = Salon.find(self.created_by)  		
  		#UserMailer.registration_by_salon_notice(self,@salon).deliver  		
  	else
		  #UserMailer.registration_notice(self).deliver
  	end
  end

end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::ApplicationController
	before_filter :authenticate_professional!
  load_and_authorize_resource

  def index
    @clients = @salon.clients

    respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @clients }
    end
  end

  def show
    @client = @salon.clients.find(params[:id])
    @associated_services = @client.associated_services.where(:salon_id => @salon)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  def new
    @client = @salon.clients.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  def edit
    @client = @salon.clients.find(params[:id])
  end

  def search
    @client = Client.where("email = ? or celphone = ?", params[:email], params[:celphone]).first
    respond_to do |format|      
      format.js {render :search}
      format.html      
    end          
  end

  def add_to_salon
    @client = Client.find(params[:client_id])
    if !@client.salons.include? current_professional.salon
      @client.salons << current_professional.salon
    end
    
    respond_to do |format|
      if @client.save
        flash[:notice] = "Cliente adicionado com sucesso!"
        format.html { redirect_to [:admin,@client] }
        format.json { render json: @client, status: :created, location: @client }
        format.js
      else        
        format.js {render "add_error"}
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @client = Client.new(params[:client])    
    generated_password = Devise.friendly_token.first(6)
    @client.password = generated_password
    @client.created_by = current_professional.salon.id
    @client.salons << @salon
    respond_to do |format|
      if @client.save
        flash[:notice] = "Cliente cadastrado com sucesso!"
        format.html { redirect_to admin_client_path(@client) }
        format.json { render json: @client, status: :created, location: @client }
        format.js
      else
        format.js {render "create_error"}
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @client = @salon.clients.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        flash[:notice] = "Cliente atualizado com sucesso!"
        format.html { redirect_to admin_client_path(@client) }
        format.json { render json: @client, status: :updated, location: @client }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    @client = Client.find(params[:id])
    @clientSalon = ClientSalon.where(:client_id => params[:id], :salon_id => @salon.id).first
    @clientSalon.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to admin_clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(current_user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end  

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/admin/clients/_client_details_modal.html.erb
<div class="modal hide fade" id="client_details" data-backdrop="static">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Adicionar Cliente</h3>
    </div>
<div class="modal-body">
    <h4 class="sub">
        <span>
            Client cadastrado no Instanapp
        </span>
    </h4>      
            <p>
            Esse email já se encontra cadastrado no Instanapp, esse cliente abaixo é o seu cliente? 
            <dl>
                <dt>Se Sim</dt>
                <dd>Por favor clique no link abaixo que diz "Adicionar aos meus clientes"</dd>
                <dt>Se Não</dt>
                <dd>Clique em "Cancelar" e digite um endereço de email diferente</dd>
            </dl>            
        </p>  
    <div class="profile">
        <%=form_tag "/admin/clients/#{@client.id}/add/to/salon" do %>
            <%=hidden_field_tag :client_id, @client.id%>
            <div class="profile-head clearfix">
                <div class="profile-info pull-left">
                    <h1 class="profile-username"><%=@client.name%></h1>
                    <ul class="profile-attributes">
                        <%if @client.city%>
                            <li><i class="icon-map-marker"></i>
                            <%=@client.city%>, <%=@client.state%></li>
                        <%end%>
                        <li><i class="icos-phone-2"></i> <%=formatted_phone(@client.celphone)%></li>
                    </ul>
                </div>
                <div class="btn-toolbar pull-right">  
                    <%=button_tag :type => "submit", :class => "btn btn-success" do %>
                        <i class='icon-users'></i> Adicionar aos meus clientes</a>
                    <%end%>
                </div>
            </div>                
        <%end%>
        
    </div>
</div>
<div class="modal-footer">
    <a href="#" class="btn" data-dismiss='modal'>Cancelar</a>    
</div>  
</div>

app/views/admin/clients/_modal_form.html.erb
<div class="modal hide fade" id="new_client">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Adicionar Cliente</h3>
  </div>
  <div class="modal-body">
    <div class="wizard-nav wizard-nav-horizontal">
      <ul>
        <li class="active">
          <a href="#registered" data-toggle="tab">
            <span>
              <i class="icon-ok-circle"></i> 
              Cliente com conta no Instanapp
            </span>
          </a>
        </li>
        <li>
          <a href="#not_registered" data-toggle="tab">
            <span>
              <i class="icon-remove-circle"></i> 
              Cliente sem conta no Instanapp
            </span>
          </a>
        </li>
      </ul>
    </div>
    <div class="tab-content client-manager-model">
      <div id="registered" class="select_client tab-pane active">
        <div class="registered-search">
          <%=render "admin/clients/search_registered_client"%>                          
        </div>
        <div class="registered-result"></div>

        
      </div>  
      <div id="not_registered" class="tab-pane">
        <div class="widget">          
          <div class="widget-content form-container">
            <%@new_client = Client.new%>
            <%= simple_form_for([:admin,@new_client],:html=>{:class=>"form-horizontal",:remote=>true}) do |f| %>
            <%=f.input :name, :label => "Nome"%>
            <%=f.input :celphone, :label => "Celular", :input_html=>{:class => "phone"}%>                      
            <%=f.input :email, :label => "E-mail"%>             
            <div class="form-actions">
              <%=f.submit "Salvar", :class => "btn btn-primary", :disable_with => "Salvando..."%>              
            </div>      
            <%end%>
          </div>
        </div>        
      </div>
    </div>    
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss='modal'>Cancelar</a>    
  </div>  
</div>

app/views/admin/clients/_next_events.html.erb
<div class="span12 widget ">        
		<div class="widget-header">
			<span class="title">
				Próximos agendamentos de <%=@client.name%>
			</span>
			<div class="toolbar">
				<%=link_to admin_events_path(:client => @client), :class => "btn btn-mini" do%>
					<i class="icon-list"></i>  Mais Agendamentos
				<%end%>
				<%=link_to easy_new_admin_events_path(:client => @client), :class => "btn btn-mini" do%>
					<i class="icon-plus"></i>  Novo Agendamento
				<%end%>				
			</div>
		</div>
		<div class="widget-content table-container">
			<table class="table table-striped dashboard-table table-flipscroll">
				<thead>
					<tr>
						<th style="width:20%">Horário</th>
						<th>Serviço</th>
						<th>Funcionário</th>
						<th>Duração</th>
						<th>Status</th>
						<th></th>
					</tr>
				</thead>
				<tbody>					
					<%@client.events.from_today_on.each do |event|%>
					<tr>
						<td>							
							<blockquote>
								<small>
									<%=event.start_at.strftime("%d de %B")%>        
								</small>
								<p>
									<%=event.start_at.strftime("%H:%M h")%>        
								</p>
								<%if event.start_at > Time.zone.now%>
								<small>                                                        
									em <%=distance_of_time_in_words(Time.zone.now,event.start_at)%>
								</small>
								<%end%>
							</blockquote>

						</td>
						<td><%=event.service.name if event.service%></td>
						<td><%=event.professional.name if event.client%></td>
						<td><%=distance_of_time_in_words(event.start_at,event.end_at)%></td>
						<td>
							<span class="badge badge-<%=event_type(event)%>">
								<%=event.status%>
							</span>
						</td>
						<td class="action-col">
							<span class="btn-group">
								<%=link_to [:admin, event], 
								:class => "btn btn-small" do%>
								<i class="icon-search"></i>

								<%end%>
								<%=link_to edit_admin_event_path(event), 
								:class => "btn btn-small" do%>
								<i class="icon-pencil"></i>

								<%end%>
								<%=link_to [:admin,event], 
								"data-method-type" => :delete, 
								:class => "btn btn-small confirmable",
								"data-message" => "Deseja realmente remover este evento?" do%>
								<i class="icon-trash"></i>

								<%end%>
							</span>
						</td>
					</tr>
					<%end%>					
				</tbody>
			</table>
		</div>	
</div>

app/views/admin/clients/_search_registered_client.html.erb
<ul id="myTab" class="nav nav-tabs">
  <li class="active">
    <a href="#email-search" data-toggle="tab">Busca por Email</a>
  </li>
  <li class="">
    <a href="#phone-search" data-toggle="tab">Busca por Celular</a>
  </li>          
</ul>
<div class="tab-content">          
  <div class="tab-pane fade active in" id="email-search">
    <%=form_tag search_admin_clients_path, :class => "form-vertical", :remote => true, :method => :get do |f|%>
    <%=hidden_field_tag :modal_search, 1%>
    <div class="formSep">
      <label>Digite o email do cliente</label>
      <div class="input-append">
        <%=text_field_tag :email%><%=submit_tag "Buscar", :class => "btn"%>  
      </div>                
      <span class="help-block">Deve ser o mesmo usado no Instanapp</span>                
    </div>
    <%end%>    
  </div>

  <div class="tab-pane fade" id="phone-search">
    <%=form_tag search_admin_clients_path, :class => "form-vertical", :remote => true, :method => :get do |f|%>
    <%=hidden_field_tag :modal_search, 1%>
    <div class="formSep">
      <label>Digite o celular do cliente</label>
      <div class="input-append">
        <%=text_field_tag :celphone,"", :class => "phone"%> <%=submit_tag "Buscar", :class => "btn"%>  
      </div>                
      <span class="help-block">Deve ser o mesmo usado no Instanapp</span>                
    </div>    
    <%end%>
  </div>          
</div>

app/views/admin/clients/_search_result.html.erb
<%if @client%>
  <div class="w-box"> 
    <div class="w-box-header"> 
      Cliente encontrado no Instanapp 
      <div class="pull-right">
        <a href="#" class="back_to_form">
          <i class="icon-arrow-left">
            Voltar  
          </i>          
        </a>
      </div> 
    </div> 
    <div class="w-box-content"> 
      <table class="table table-striped table_vam no-th"> 
        <tbody> 
          <tr class="client_info" data-id="<%=@client.id%>"> 
            <td> 
              <img alt="" src="http://placehold.it/40x40/efefef" class="thumbnail"> 
            </td> 
            <td>
              <%=escape_javascript(@client.name)%>
            </td> 
            <td> 
              <%=formatted_phone(@client.celphone)%> 
            </td> 
            <td><%=@client.email%></td> 
            <td><%=@client.city%></td> 
          </tr> 
        </tbody>
      </table> 
      <%=link_to 'Adicionar Cliente','#', :class=> 'btn btn-primary', :disable_with => 'Salvando...'%>
    </div> 
  </div>
<%else%>
  <div>
    <div class="alert alert-danger fade in">
      <strong>Cliente não cadastrado</strong><br>
      O cliente não foi encontrado. É possível que este usuário não possua cadastro no Instanapp
    </div>
    <a href="#" class="back_to_form">
      <i class="icon-arrow-left">
        Voltar  
      </i>      
    </a>
  </div>
<%end%>

app/views/admin/clients/_top_menu.html.erb
<%=content_for :top_menu do%>
	<%if action_name != "index"%>
		<%=link_to admin_clients_path, :class => "item" do%>
		<span class="item-icon">
			<i class="icon-list"></i>
		</span>
		<span class="item-label">Listar Clientes</span>								
		<%end%>
	<%end%>
	<%if action_name != "new"%>
		<%=link_to new_admin_client_path, :class => "item" do%>
		<span class="item-icon">
			<i class="icon-plus"></i>
		</span>
		<span class="item-label">Novo Cliente</span>								
		<%end%>
	<%end%>
<%end%>

app/views/admin/clients/add_to_salon.js.erb
$("<option value='<%=@client.id%>' selected='selected'><%=@client.name%></option>").appendTo("#client");
$("#client").trigger("liszt:updated");
$("#new_client").modal('hide');
var noty = noty(
	{
		text: '<%=flash.discard(:notice)%>',
		type: 'success',
		timeout: 4000
	}
);

app/views/admin/clients/create.js.erb
$("<option value='<%=@client.id%>' selected='selected'><%=@client.name%></option>").appendTo("#client");
$("#client").trigger("liszt:updated");
$("#new_client").modal('hide');
var noty = noty(
	{
		text: '<%=flash.discard(:notice)%>',
		type: 'success',
		timeout: 4000
	}
);

app/views/admin/clients/destroy.js.erb
$("#confirmation-modal").modal("hide");
var list_item = $("#c_<%=escape_javascript(@clientSalon.client.id.to_s)%>");
if (list_item.length > 0){
	list_item.hide("slow");
} else{
	window.location = "<%=escape_javascript(admin_clients_path)%>";
}

app/views/admin/clients/edit.html.erb
<%=render "top_menu"%>

<header>
	<h2>Editar Cliente</h2>
</header>

<div id="main-content">
	<%=render "context_menu"%>
	<div class="row-fluid">
		<div class="span12 widget">
			<div class="widget-header">
				<span class="title">Dados do Cliente</span>
			</div>
			<div class="widget-content form-container">
        <%= simple_form_for([:admin,@client],:html=>{:class=>"form-horizontal"}) do |f| %>
        <fieldset>
					<legend>Dados Obrigatórios</legend>
					<%=f.input :name, :label => "Nome", :hint => "Digite apenas o primeiro e o último nome"%>					
					<%=f.input :email, :label => "Email", :hint => "Se o cliente não possuir email, deixe esse campo em branco"%>
					<%=f.input :celphone, :label => "Telefone Principal", :hint => "de preferência o número do seu celular", :input_html => {:class => "phone"}%>
					<%=f.input :landphone, :label => 'Telefone Adicional', :hint => "seu telefone fixo, de trabalho ou um segundo número de celular", :input_html => {:class=> 'phone'} %>
				</fieldset>
				<fieldset>
					<legend>Dados Adicionais</legend>
					<div class="control-group">
                        <%=f.label :zipcode, "CEP", :class => "control-label"%>
                        <div class="controls">
                            <%=f.input_field :zipcode , :class=>'zipcode'%><%=image_tag "/assets/small_loader.gif", :class => 'zipcode_loading input_ajax_loading'%>
                        </div>
                    </div>
                    <%=f.input :address, :label => "Endereço", :input_html => {:class => "address"}%>
                    <%=f.input :house_number, :label => 'Número', :input_html => {:class => "house_number"}%>
                    <%=f.input :complement, :label => 'Compelemento', :input_html => {:class => "complement"}%>
                    <%=f.input :region, :label => 'Bairro', :input_html => {:class => "neighborhood"}%>
                    <%=f.input :city, :label => 'Cidade', :input_html => {:class => "city"}%>
                    <%=f.input :state, :label => 'Estado', :input_html => {:class => "state"}%>
                                        
				</fieldset>        
				<div class="form-actions">
					<%=f.submit "Salvar", :class => "btn btn-primary", :disable_with => "Salvando..."%>
					<%=link_to "Cancelar", :back, :class => "btn"%>
				</div>			
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/admin/clients/new.html.erb
<%=render "top_menu"%>

<header>
	<h2>Detalhes do cliente</h2>	
</header>

<div id="main-content">
	<%=render "context_menu"%>
	<div class="row-fluid">
		<div class="span12 widget new-client">
			<div class="widget-header">
				<span class="title">Dados do Cliente</span>
			</div>
			<div class="widget-content form-container">
				<%= simple_form_for([:admin,@client],:html=>{:class=>"form-horizontal"}) do |f| %>
				<fieldset>
					<legend>Dados de Contato</legend>
					<%=f.input :name, :label => "Nome", :hint => "Digite apenas o primeiro e o último nome"%>					
					<div class="control-group string required">
                        <%=f.label :email, "Email", :class => "control-label required string"%>
                        <div class="controls">
                            <%=f.input_field :email%><%=image_tag "/assets/small_loader.gif", :class => "input_ajax_loading"%>
                            <p class="help-block">Se o cliente não possuir email deixe esse campo em branco</p>
                        </div>
                    </div>
                    <%=f.input :celphone, :label => "Telefone Principal", :hint => "de preferência o número do celular", :input_html => {:class => "phone"}%>
					<%=f.input :landphone, :label => 'Telefone Adicional', :hint => "telefone fixo, de trabalho ou um segundo número de celular", :input_html => {:class=> 'phone'} %>					
				</fieldset>
				<fieldset>
					<legend>Dados Adicionais</legend>
					<div class="control-group">
                        <%=f.label :zipcode, "CEP", :class => "control-label"%>
                        <div class="controls">
                            <%=f.input_field :zipcode , :class=>'zipcode'%><%=image_tag "/assets/small_loader.gif", :class => 'zipcode_loading input_ajax_loading'%>
                        </div>
                    </div>
                    <%=f.input :address, :label => "Endereço", :input_html => {:class => "address"}%>
                    <%=f.input :house_number, :label => 'Número', :input_html => {:class => "house_number"}%>
                    <%=f.input :complement, :label => 'Compelemento', :input_html => {:class => "complement"}%>
                    <%=f.input :region, :label => 'Bairro', :input_html => {:class => "neighborhood"}%>
                    <%=f.input :city, :label => 'Cidade', :input_html => {:class => "city"}%>
                    <%=f.input :state, :label => 'Estado', :input_html => {:class => "state"}%>                    
				</fieldset>
				
				<div class="form-actions">
					<%=f.submit "Salvar", :class => "btn btn-primary", :disable_with => "Salvando..."%>
					<%=link_to "Cancelar", :back, :class => "btn"%>
				</div>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/admin/clients/search.js.erb
var modal_search = "<%=escape_javascript(params[:modal_search])%>";

//There are 2 types of search, the search when adding an event and the normal search when adding a user
if (modal_search == 1){
	var client_selection = "<%= escape_javascript(render 'search_result')%>";
	var shown_div = $("#new_client .modal-body .select_client.active");
	var modal = $("#new_client");
	shown_div.find(".registered-search").hide();
	$(shown_div).find(".registered-result").html(client_selection).fadeIn();
	var submit_button = "<%=escape_javascript(link_to('Adicionar Cliente','#', :class=> 'btn btn-primary', :disable_with => 'Salvando...'))%>"
	modal.modal("loading");	
} else {
	$("#client_email").parent().find("img").fadeOut();	
	<%if @client%>		
		var modal = "<%=escape_javascript(render('client_details_modal'))%>";
		$("#client_details").remove();
		$("body").prepend(modal);
		$("#client_details").modal();		
	<%end%>
}

app/views/admin/clients/search_not_found.js.erb
var client_selection = '<div><div class="alert alert-danger fade in"> \
                                    <a href="#" class="close" data-dismiss="alert">×</a> \
                                    <strong>Cliente não cadastrado</strong><br> \
                                    O cliente não foi encontrado. É possível que este usuário não possua cadastro no Instanapp \
                                </div><a href="#" class="back_to_form">Voltar</a></div>';
var shown_div = $("#new_client .modal-body .select_client:not(.hidden)");
var modal = $("#new_client");
shown_div.find("form").hide();
$(client_selection).hide().appendTo(shown_div).fadeIn();
modal.modal("loading");

app/views/admin/clients/show.html.erb
<%=render "top_menu"%>

<header>
	<h2>Detalhes do cliente</h2>	
</header>

<div id="main-content">
	<%=render "context_menu"%>
	<div class="row-fluid">
		<div class="form-horizontal widget span6">
			<div class="widget-header">
				<span class="title">Informações do Cliente</span>
				<div class="toolbar">
					<%=link_to edit_admin_client_path(@client), :class => "btn btn-gebo btn-mini" do%>
					<i class="icon-edit"></i> Editar Cliente
					<%end%>
				</div>
			</div>

			<div class="widget-content table-container">
				<table class="table table-detail-view">
					<tbody>
						<tr>
							<th>Nome</th>
							<td><%=@client.name%></td>
						</tr>
						
						<tr>
							<th>E-mail</th>
							<td><%=@client.email%></td>
						</tr>
						<tr>
							<th>Telefone Principal</th>
							<td><%=@client.celphone%></td>
						</tr>						
						<%if @client.landphone%>
						<tr>
							<th>Telefone Adicional</th>
							<td><%=@client.landphone%></td>
						</tr>
						<%end%>		
						<%if @client.address%>
						<tr>
							<th>Endereço</th>
							<td>
								<address>                										
									<%=@client.address%>, <%=@client.house_number%>               
									<br />
									<%=@client.city%>/<%=@client.state%>   <%=@client.zipcode%>
								</address>
							</td>
						</tr>
						<%end%>
					</tbody>					
				</table>
			</div>		
		</div>
		<%=render "/admin/client_services/index"%>
	</div>
	<%if @client.events.from_today_on.length > 0%>
		<div class="row-fluid">
			<%=render "next_events"%>	
		</div>
	<%end%>
</div>