config/routes.rb
Smartsalon::Application.routes.draw do

  get "client_services/index"

  get "client_services/new"

  get "dashboard/index"

  get "dashboard" => "dashboard#index"

  post "favorites" => "favorites#create"

  delete "favorites/:id" => "favorites#destroy"

  resources :settings

  namespace :landing do
    root :to => "pages#index"
    get "pages/index"
    get "pages/about"
  end

  namespace :admin do    
    root :to => "dashboard#index"
    post "payments/notification" => "payments#notification", :as => "payment_notification"
    get 'dashboard' => "dashboard#index"
    
    resources :services do
      collection do
        get 'get_services'
        get 'search'
      end
      resources :client_services
    end      
    
    resources :events do      
      collection do
        get "easy/new" => "events#easy_new"
        post "easy/new" => "events#easy_create"
        get 'get_events'
        get 'search'
        get 'calendar'
      end
      member do
        post "edit" => "events#update"
      end
    end
    
    resources :professionals do
      collection do
        post "search_zipcode" => "professionals#search_zipcode"
      end
      put "update_password" => "professionals#update_password", :as => "update_password", :on => :member
      resources :working_times
      resources :professional_services
    end
    
    resources :salons do
      collection do
        post "search_zipcode" => "salons#search_zipcode"
      end
      post "payments/checkout" => "payments#checkout", :as => "payments_checkout"
      get "payments/:payment_id/receipt" => "payments#receipt", :as => "payments_receipt"
    end
    
    resources :clients do
      post "add/to/salon" => "clients#add_to_salon", :as => "add_to_salon"
      collection do
        get "search"
      end
      resources :client_services      
    end
    
    resources :client_services
  end

  devise_for :clients, :controllers =>
  {
    :registrations => "registrations"
  }

  devise_for :users, :controllers => 
  { 
    :registrations => "registrations" ,
    :sessions => "sessions"
  }

  devise_for :professionals, 
  :controllers => 
  { 
    :registrations => "registrations" ,
    :sessions => "admin/sessions"
  }

  resources :clients do
    resources :events
  end

  resources :salons do
    get 'page/:page', :action => :index, :on => :collection
    post "events/:id/edit" => "events#update"
    post "events/new" => "events#create"
    resources :events
  end

  resources :events

  resources :users

  root :to => "dashboard#index"

end

app/models/service.rb
#encoding: utf-8

class Service < ActiveRecord::Base
  include ActiveModel::Validations
  
  attr_accessible :duration, :name, :price
  has_many :professional_services, :dependent => :destroy
  has_many :professionals, :through => :professional_services
  has_many :events
  has_many :client_services
  has_many :clients, :through => :client_services
  belongs_to :salon
  validates :name, :duration, presence: true
  validates :price, numericality: {greater_than: 0}, :allow_blank => true
  validates :duration, numericality: {greater_than: 0}
  validates_with DivisibleValidator

  def preferred_duration(client)
  	client_service = self.client_services.where(:client_id => client).first
  	if client_service
  		client_service.duration
  	else
  		self.duration
  	end
  end

  def associated_clients
    self.client_services.joins(:salon)
  end
end

app/controllers/admin/services_controller.rb
#encoding : utf-8
class Admin::ServicesController < Admin::ApplicationController
  before_filter :authenticate_professional! 
  load_and_authorize_resource

  def index
    @services = @salon.services
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }    

    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = @salon.services.find(params[:id])
    @associated_clients = @service.associated_clients.where(:salon_id => @salon)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])
    @service.salon = current_professional.salon

    respond_to do |format|
      if @service.save
        format.html { redirect_to admin_service_path(@service), notice: 'Serviço criado com sucesso' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])
    @service.salon = current_professional.salon

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to admin_service_url, notice: 'Serviço atualizado com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy

    confirm_delete = params[:confirm_delete]
    @service = Service.find(params[:id])

    if @service.events.length > 0 && !confirm_delete
      @service.errors[:base] << "Existem agendamentos para este serviço. " + 
        "A exclusão do serviço vai provocar o cancelamento desses eventos." + 
        "Você deseja confirmar a operação?"

      respond_to do |format|
        format.js { render "destroy_error"}
        format.html { redirect_to admin_services_url }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    else
      @service.destroy

      @service.events.each do |e|
        e.update_attributes(:reschedule => true)
        if(e.client)
          Notifier.client_event_canceled(e).deliver
        end
        if(e.professional)
          Notifier.professional_event_canceled(e).deliver
        end
      end

      respond_to do |format|
        format.html { redirect_to admin_services_url }
        format.json { head :no_content }
        format.js
      end      
    end     
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.json
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to admin_service_path(@service), notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to admin_service_url, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to admin_services_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_context_menu.html.erb
<div class="row-fluid">
  <div class="switch-board-round">
    <ul class="clearfix">
      <li class="<%=active_action('services','new')%>">
        <%=link_to new_admin_service_path, :class => "tip-top", :rel => "tooltip", "data-original-title" => "Novo Serviço" do%>  
          <span class="icon-plus"></span>
        <%end%>
      </li>
      <li class="<%=active_action('services','index')%>">
        <%=link_to admin_services_path, :class => "tip-top", :rel => "tooltip", "data-original-title" => "Listar Serviços" do%>  
          <span class="icon-list"></span>
        <%end%>
      </li>
      <%if action_name == "show"%>
        <li>
        <%=link_to edit_admin_service_path(@service), :class => "tip-top", :rel => "tooltip", "data-original-title" => "Editar Serviço" do%>  
          <span class="icon-edit"></span>
        <%end%>
      </li>
      <%end%>
   </ul>
 </div>
</div>

app/views/admin/services/_form.html.erb
<%= simple_form_for([:admin,@service],:html=>{:class=>"form-horizontal", :id=> "new_admin_service_form"}) do |f| %>        
<% if @service.errors.any? %>
<div class="alert alert-danger fade in">
  <a href="#" class="close" data-dismiss="alert">×</a>
  <strong>Por favor corrija os erros abaixo:</strong><br>
  <p class="error-message">
    <% @service.errors.full_messages.each do |msg| %>
    <%= msg %>
    <br>
    <% end %>
  </p>
</div>        
<% end %>

<%=f.input :name, :label => 'Nome'%>


<%=f.input :price, :label => "Preço", :wrapper => :append_prepend do %>
  <span class="add-on">R$</span>
  <%=f.input_field :price, :class => "input-mini"%>
  <span class="add-on">reais</span>   
<%end%>
<%=f.input :duration, :label => "Duração", :wrapper => :append do%>
  <%=f.input_field :duration, :class => "input-mini"%>
  <span class="add-on">minutos</span>  
<%end%>
<div class="form-actions">
  <%=f.submit "Salvar", :class => "btn btn-primary"%>
  <%=link_to "Cancelar", :back, :class => "btn"%>
</div>
<%end%>          

app/views/admin/services/_top_menu.html.erb
<%=content_for :top_menu do%>
	<%if action_name != "index"%>
		<%=link_to admin_services_path, :class => "item" do%>
		<span class="item-icon">
			<i class="icon-list"></i>
		</span>
		<span class="item-label">Listar Serviços</span>								
		<%end%>
	<%end%>
	<%if action_name != "new"%>
		<%=link_to new_admin_service_path, :class => "item" do%>
		<span class="item-icon">
			<i class="icon-plus"></i>
		</span>
		<span class="item-label">Novo Serviço</span>								
		<%end%>
	<%end%>
<%end%>

app/views/admin/services/destroy.js.erb
$("#confirmation-modal").modal("hide");
var list_item = $("#s_<%=escape_javascript(@service.id.to_s)%>");
if (list_item.length > 0){
	list_item.hide("slow");
} else{
	window.location = "<%=escape_javascript(admin_services_path)%>";
}

app/views/admin/services/destroy_error.js.erb
var html = '<div class="alert alert-block alert-warning fade in"> \
	<h4 class="alert-heading">Atenção!</h4> \
	<p> \
		<%=@service.errors[:base][0]%> \
	</p> \
</div>';

$("#confirmation-modal .modal-body").html(html);

var link_div = $("#confirmation-modal .link");

link_div.attr("data-destination",link_div.attr("data-destination") + "?confirm_delete=1");

app/views/admin/services/edit.html.erb
<%=render "top_menu"%>

<header>
	<h2>Editar Serviço</h2>
</header>

<div id="main-content">
	<%=render "context_menu"%>
	<div class="row-fluid">
		<div class="span12 widget">
			<div class="widget-header">
				<span class="title">Dados do Serviço</span>
			</div>
			<div class="widget-content form-container">				
				<%=render "form"%>
			</div>
		</div>
	</div>
</div>

app/views/admin/services/index.html.erb
<%=render "top_menu"%>

<header>
	<h2>Listar Serviços</h2>
</header>

<div id="main-content">
	<%=render "context_menu"%>
	<div class="row-fluid">		
		<div class="span12 widget">
			<div class="widget-header">
				<span class="title">Serviços</span>
				<div class="toolbar">					
					<%=link_to new_admin_service_path, :class => "btn btn-gebo btn-mini" do%>
						<i class="icon-plus"></i>
						Novo Serviço
					<%end%>
				</div>
			</div>
			<div class="widget-content table-container">
				<table class="table table-striped form-inline table-flipscroll" id="services_list">
					<thead>
						<tr>
							<th>Nome</th>
							<th>Preço</th>
							<th>Duração</th>							
							<th></th>		
						</tr>
					</thead>
					<tbody>

						<%@services.each do |s|%>
							<tr id="s_<%=s.id.to_s%>">					
								<td><%=s.name%></td>
								<td><%= s.price ? number_to_currency(s.price.real) : "  -" %></td>					
								<td><%=distance_of_time(s.duration * 60, :locale => "pt-BR")%></td>
								<td class="action-col">
									<span class="btn-group visible-phone">
										<%=link_to [:admin, s], :class => "btn btn-small" do%>
											<i class="icon-search"></i>											
										<%end%>
										<%=link_to edit_admin_service_path(s), :class => "btn btn-small" do%>
											<i class="icon-pencil"></i>											
										<%end%>
										<%=link_to [:admin,s], "data-method-type" => :delete, :class => "btn btn-small confirmable",
										"data-message" => "Deseja realmente remover este serviço?" do%>
											<i class="icon-trash"></i>											
										<%end%>
									</span>
									<span class="btn-group hidden-phone">
										<%=link_to [:admin, s], :class => "btn btn-small btn-primary" do%>
											<i class="icon-search"></i>
											Detalhes
										<%end%>
										<%=link_to edit_admin_service_path(s), :class => "btn btn-small btn-warning" do%>
											<i class="icon-pencil"></i>
											Editar
										<%end%>
										<%=link_to [:admin,s], "data-method-type" => :delete, :class => "btn btn-small btn-danger confirmable",
										"data-message" => "Deseja realmente remover este serviço?" do%>
											<i class="icon-trash"></i>
											Remover
										<%end%>
									</span>
								</td>
							</tr>
						<%end%>
					</tbody>					
				</table>	
			</div>
		</div>
	</div>	
</div>

app/views/admin/services/new.html.erb
<%=render "top_menu"%>

<header>
	<h2>Novo Serviço</h2>
</header>

<div id="main-content">
	<%=render "context_menu"%>
	<div class="row-fluid">
		<div class="span12 widget">
			<div class="widget-header">
				<span class="title">Dados do Serviço</span>
			</div>
			<div class="widget-content form-container">				
				<%=render "form"%>
			</div>
		</div>
	</div>
</div>

app/views/admin/services/show.html.erb
<%=render "top_menu"%>

<header>
	<h2>Detalhes do Serviço</h2>
</header>

<div id="main-content">
	<%=render "context_menu"%>
	<div class="row-fluid">
		<div class="form-horizontal widget span6">
			<div class="widget-header">
				<span class="title">Informações do Serviço</span>
				<div class="toolbar">
					<%=link_to edit_admin_service_path(@service), :class => "btn btn-gebo btn-mini" do%>
					<i class="icon-edit"></i>
					Editar Serviço
					<%end%>
				</div>
			</div>

			<div class="widget-content table-container">
				<table class="table table-detail-view">
					<tbody>
						<tr>
							<th>Nome</th>
							<td><%=@service.name%></td>
						</tr>
						<tr>
							<th>Preço</th>
							<td><%= number_to_currency @service.price if @service.price%></td>
						</tr>					
						<tr>
							<th>Duração</th>
							<td><%=distance_of_time(@service.duration*60)%></td>
						</tr>
					</tbody>					
				</table>
			</div>		
		</div>
		<!-- Informações dos tempos específicos para o serviço do cliente -->
		<%=render "/admin/client_services/index"%>
	</div>

		
		
</div>