config/routes.rb
Smartsalon::Application.routes.draw do

  get "client_services/index"

  get "client_services/new"

  get "dashboard/index"

  get "dashboard" => "dashboard#index"

  post "favorites" => "favorites#create"

  delete "favorites/:id" => "favorites#destroy"

  resources :settings

  namespace :landing do
    root :to => "pages#index"
    get "pages/index"
    get "pages/about"
  end

  namespace :admin do    
    root :to => "dashboard#index"
    post "payments/notification" => "payments#notification", :as => "payment_notification"
    get 'dashboard' => "dashboard#index"
    
    resources :services do
      collection do
        get 'get_services'
        get 'search'
      end
      resources :client_services
    end      
    
    resources :events do      
      collection do
        get "easy/new" => "events#easy_new"
        post "easy/new" => "events#easy_create"
        get 'get_events'
        get 'search'
        get 'calendar'
      end
      member do
        post "edit" => "events#update"
      end
    end
    
    resources :professionals do
      collection do
        post "search_zipcode" => "professionals#search_zipcode"
      end
      put "update_password" => "professionals#update_password", :as => "update_password", :on => :member
      resources :working_times
      resources :professional_services
    end
    
    resources :salons do
      collection do
        post "search_zipcode" => "salons#search_zipcode"
      end
      post "payments/checkout" => "payments#checkout", :as => "payments_checkout"
      get "payments/:payment_id/receipt" => "payments#receipt", :as => "payments_receipt"
    end
    
    resources :clients do
      post "add/to/salon" => "clients#add_to_salon", :as => "add_to_salon"
      collection do
        get "search"
      end
      resources :client_services      
    end
    
    resources :client_services
  end

  devise_for :clients, :controllers =>
  {
    :registrations => "registrations"
  }

  devise_for :users, :controllers => 
  { 
    :registrations => "registrations" ,
    :sessions => "sessions"
  }

  devise_for :professionals, 
  :controllers => 
  { 
    :registrations => "registrations" ,
    :sessions => "admin/sessions"
  }

  resources :clients do
    resources :events
  end

  resources :salons do
    get 'page/:page', :action => :index, :on => :collection
    post "events/:id/edit" => "events#update"
    post "events/new" => "events#create"
    resources :events
  end

  resources :events

  resources :users

  root :to => "dashboard#index"

end

app/controllers/admin/events_controller.rb
#encoding: utf-8

class Admin::EventsController < Admin::ApplicationController
  include NewEvent
  before_filter :authenticate_professional!
  before_filter :load_salon

  def index    
    @events = @salon.events.includes(:client,:professional)
    @events = @events.today if params[:date] == "today"
    @events = @events.mine(current_professional.id) if params[:professional]    
    
    
    if params[:past_events]
      @events = @events.scoped
    else
      @events = @events.from_today_on
    end
    respond_to do |format|
      format.js      
      format.json {render json: EventsDatatable.new(view_context,@salon)}
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  def calendar
    @events = @salon.events.order("start_at").includes(:client,:professional).today
    @professionals_with_services = current_professional.salon.professionals.includes(:professional_services).includes(:events).where("professional_services.service_id is not null")  
    respond_to do |format|
      format.html
    end
  end

  def get_events
    @events = current_professional.events.where(
      "start_at >= ? and end_at <= ?",
      Time.at(params['start'].to_i).to_formatted_s(:db),
      Time.at(params['end'].to_i).to_formatted_s(:db) 
      )
    events = [] 
    @events.each do |event|
      events << {
        :id => event.id, 
        :title => event.title, 
        :description => event.description,
        :url => url_for(:controller => 'admin/events', :action => "show", :id => event.id),
        :start => "#{event.start_at.iso8601}", 
        :end => "#{event.end_at.iso8601}",
        :allDay => false,
        :shown_title => "<b>#{event.start_at.strftime('%H:%M')}</b> - #{event.title}"
      }
    end
    render :text => events.to_json
  end

  def search
    @events = Event.order("start_at").includes(:client,:professional).where("start_at >= ?", Time.zone.today)

    respond_to do |format|
      format.js
      format.json
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  def new
    @event = Event.new
    @clients = @salon.clients
    @client = Client.find(params[:client]) unless params[:client].blank?
    #delay = (60 - (DateTime.now.min))%5
    if !params[:day].nil?
      @event.start_at = params[:day] + " " + DateTime.now.strftime("%H:%M") unless params[:day].nil?
      @event.start_at+=minutes.delay
    end
    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.xml  { render :xml => @event }
    end
  end

  def easy_new
    @event = Event.new
    @clients = @salon.clients
    @client = Client.find(params[:client]) unless params[:client].blank?
    find_new_event
    respond_to do |format|
      format.html # new.html.erb
      format.js {render "/events/new"}
      format.xml  { render :xml => @event }
    end
  end

  def create
    confirm_conflicts = params[:confirm_conflicts]    
    #params[:event].delete(:confirm_conflicts)    
    @event = Event.new(params[:event])
    @event.salon = @salon    
    
    #Adding the professional to the event        
    @event.professional_id = params[:professional] || current_professional.id    
    
    #Adding the service to the event
    @event.service_id = params[:service] if params[:service] && params[:service] != ""

    #Adding the client to the event if exists
    @event.client_id = params[:client] if params[:client] && params[:client] != ""

    #Checking if it's to save the event event with conflicts    
    if confirm_conflicts == "1"
      if @event.save(:validate => false)
        conflicted_events = @event.find_conflicts
        conflicted_events.each do |e|
          e.update_attributes(:reschedule => true)
          if(e.client)
            puts "Notify client about canceled event"
            #Notifier.client_event_reschedule_notification(e).deliver
          end
          if(e.professional)   
            puts "notify professional about canceled event"
            #Notifier.professional_event__reschedule_notification(e).deliver
          end
        end
        respond_to do |format|                
          format.html { redirect_to([:admin,@event], :notice => 'Agendamento criado com sucesso') }
          format.xml  { render :xml => @event, :status => :created, :location => @event }
        end
      end
    else
      respond_to do |format|
        if @event.save
          flash[:notice] = 'Agendamento criado com sucesso!'
          format.js { render js: %(window.location.href='#{admin_event_path @event}')}
          format.html { redirect_to( [:admin, @event] ) }
          format.xml  { render :xml => @event, :status => :created, :location => @event }
        else          
          format.js do 
            #Check if there are errors            
            if @event.errors[:base].empty? || @event.errors.size > 1
              render "create_error"
            else
              render "confirm_conflicts"
            end            
          end
          format.html { render :action => "new" }
          format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  def easy_create
    @event = Event.new(
      :end_at => params[:end_at], 
      :start_at => params[:start_at]
      )
    salon = @salon
    professional = salon.professionals.find(params[:professionals])
    service = professional.services.find(params[:service])
    client = salon.clients.find(params[:client])
    @event.title = service.name
    @event.description = "#{service.name} marcado(a) pelo funcionário #{current_professional.name} via internet, 
    na: #{DateTime.now.strftime("%A, %d de %B às %H:%M")}"
    @event.created_by = "Professional"
    @event.service = service
    @event.salon = salon
    @event.professional = professional
    @event.client = client
    @event.service_to_client_event = true
    respond_to do |format|
      if @event.save
        format.js
        format.html { redirect_to([:admin,@event], :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        puts @event.errors.inspect      
        format.js {render "create_error"}
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @event = Event.includes(:client,:professional,:service).find(params[:id])        
    if !params[:service] && !params[:professionals]
      @service = @event.service
      @service_professionals = @event.professional
    end
    @client = @event.client unless params[:client]
    @clients = @salon.clients    
    find_new_event    
    respond_to do |format|
      format.html
      format.js {render "/events/new"}
      format.xml  { render :xml => @event }
    end    
  end

    # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])
    @event.professional = @salon.professionals.find(params[:professionals])
    @event.service = @event.professional.services.find(params[:service])
    @event.client = @salon.clients.find(params[:client])
    @event.end_at = params[:end_at]
    @event.start_at = params[:start_at]
    @event.reschedule = false
    respond_to do |format|
      if @event.save        
        flash[:notice] = "Evento alterado com sucesso"
        format.html { redirect_to([:admin,@event])}
        format.xml  { head :ok }
        format.js {render "update"}
      else
        flash[:alert] = "Houve um erro ao tentar alterar seu evento"
        format.js {render :js => "window.location.reload()"}
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end


  def show
    @event = @salon.events.find(params[:id])
    respond_to do |format|
      format.html
      format.js
      format.xml  { render :xml => @event }
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    #Instead of destroying the event set it to Canceled
    #@event.destroy
    @event.update_attribute(:status,"Cancelado")

    respond_to do |format|

      if(@event.client)
        Notifier.client_event_canceled(@event).deliver
      end
      if(@event.professional)   
        Notifier.professional_event_canceled(@event).deliver
      end

      flash[:notice] = "Evento cancelado com sucesso!"
      format.html { redirect_to(events_url) }
      format.js
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
#encoding: utf-8

module EventsHelper      
      
      def add_to_valid_times(time)            
            @working_times.each do |wt|
                  if time.hour >= wt.from_time.hour &&
                        time.hour < wt.to_time.hour
                        @valid_times << time
                        return
                  end
            end            
      end

      def format_date_header(date)
            if date == Time.zone.today
                  "Hoje"
            elsif date == Time.zone.today.tomorrow
                  "Amanhã"
            else
                  date.strftime("%d de %B")
            end
      end

      def isavailable_mod(events, myDate, params = {})                        
            start_hour = 0
            start_min = 0      
            professional = params[:professionals]
            service = params[:service]         
            client = params[:client]
            @working_times = professional.working_times.where(:day => myDate.wday)
            @valid_times = []
            if 
                  (
                  session[:new_start_date] &&
                  session[:new_start_date].day == myDate.day &&
                  session[:new_start_date].month == myDate.month &&
                  session[:new_start_date].year == myDate.year
                  )
                        start_hour = session[:new_start_date].hour
                        start_min = session[:new_start_date].min
                        session[:new_start_date] = nil
            end            
            end_time = 23
            end_min = 59
            intervalInMinutes = service.preferred_duration(client)
            actual_date = Time.zone.local(myDate.year,myDate.month,myDate.day, start_hour, start_min)            
            end_date = Time.zone.local(myDate.year,myDate.month,myDate.day, end_time, end_min)            
            if actual_date.to_date == Time.zone.today
                  actual_date += (DateTime.now.hour).hours
                  actual_date += service.duration.minutes
            end                       
            i = 0;            
            puts actual_date
            while i < events.length && actual_date <= (end_date - intervalInMinutes.minutes) do
                  puts events[i].start_at
                  puts actual_date
                  diference = (events[i].start_at - actual_date)/60
                  puts diference
                  puts "Entrou no while"
                  if diference >= intervalInMinutes
                        add_to_valid_times(actual_date)
                        puts "Adicionou o #{actual_date} aos horarios válidos"
                        if diference < (intervalInMinutes * 2)
                              actual_date = events[i].end_at
                              i+=1
                        else
                              actual_date += intervalInMinutes.minutes
                        end
                  else
                        puts "Caiu no else ao inves de adicionar aos validos"
                        puts "#{diference} | #{intervalInMinutes}"
                        if (events[i].end_at.minus_with_coercion(actual_date)/60).to_i > 0
                              actual_date = events[i].end_at      
                        else
                              actual_date += intervalInMinutes.minutes
                        end                        
                        i+=1
                  end
            end

            while actual_date <= (end_date - intervalInMinutes.minutes) do
                  add_to_valid_times(actual_date)
                  #puts "Adicionou p #{actual_date} aos horarios validos pq nao existem mais eventos"
                  actual_date += intervalInMinutes.minutes
            end

            if    
                  (
                        actual_date.day != end_date.day ||
                        actual_date.month != end_date.month ||
                        actual_date.year != end_date.year
                  )
                  session[:new_start_date] = actual_date;
            end
            html = "<ul>"
            
            @valid_times.each do |time|
                  html << "<li>"
                  link_params = {
                              :professionals => professional,
                              :service => service,
                              :client => client,
                              :start_at => time,
                              :end_at => intervalInMinutes.minutes.since(time)                                    
                  }
                  html << link_to(
                              time.strftime("%H:%M"), link_params,
                              {                                    
                                    "data-message" => "Deseja realmente marcar um(a) <b>#{service.name}</b> com <b>#{professional.name}</b> para #{time.strftime('%A, dia %d de %B às %H:%M')}?",
                                    :class => "new-event-link confirmable"
                              } 
                        )
                  html << "</li>"
            end
            html << "</ul>"
            html
      end
end

app/views/admin/events/_calendar_view.html.erb
<div id="calendar_view">
<div class="row-fluid">
	<div class="widget span12 day-view">
		<div class="widget-header light">
			<span class="title">            
				Eventos de Hoje
			</span>
		</div>
		<div class="widget-content events_date_list" id="calendar_events_list">
			
				<div class="time_col" id="time_col">
					<ul>
						<%current_time = Time.zone.parse("00:00")%>
						<%end_time = Time.zone.parse("24:00")%>            
						<%interval = 15%>							
						<%while current_time < end_time%>
						<li>
							<span class="time">
								<%=current_time.strftime("%H:%M")%>    
							</span>                                
						</li>
						<%current_time += interval.minutes%>
						<%end%>
					</ul>
				</div>
				<div class="events_area">
					<ul class="professionals_header" id="professionals_header">						
						<%@professionals_with_services.each do |professional|%>
						<li>
							<%=professional.name%>
						</li>
						<%end%>
					</ul>					

					<%@professionals_with_services.each do |professional|%>
					<div class="event_col">
						<ul>
							<%=day_view_events(professional.events).html_safe%>    
						</ul>
					</div>											
					<%end%>
				</div>	
				
			
		</div>

	</div>
</div>
</div>

app/views/admin/events/_choose_professional.html.erb
<%@professionals ||= @salon.professionals%>
<%@professional ||= current_professional%>
<div class="formSep" id="manual-event-choose-professional">
	<div class="row-fluid form-inline">
		<p>
			<span class="label label-inverse">Selecione o funcionário:</span>
		</p>
		
		<%= select_tag(:professional, 
			options_for_select(@professionals.collect{ |s| [s.name, s.id] }, @professional.id),
			:include_blank => true, 
			:class => "chzn_a", 
			"data-placeholder" => "Selecione o funcionário"
			) %>				
		</div>
	</div>

app/views/admin/events/_confirm_conflicts.html.erb
<%= simple_form_for([:admin,@event], :id=> "confirm_create_event_form") do |f| %>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h3>A criação desse evento gerará conflitos</h3>
</div>
<div class="modal-body">
	<div class="hide">
		<%=f.input :title%>
		<%=f.input :start_at, :as => :string%>
		<%=f.input :end_at, :as => :string%>
		<%=f.association :client %>
		<%=f.association :service %>
		<%=f.association :professional %>
		<%=hidden_field_tag "confirm_conflicts", 1%>
	</div>
	<div class="alert alert-block alert-warning fade in">
		<h4 class="alert-heading">Atenção!</h4>
		<p>
			<%=@event.errors[:base][0]%>
		</p>			    
	</div>
	<div class="modal-footer">
		<a href="#" class="btn btn-inverse" data-dismiss='modal'>Cancelar</a>
		<%=f.submit "Confirmar Agendamento", :class=> "btn btn-primary"%>    
	</div>		
</div>
<%end%>

app/views/admin/events/_context_menu.html.erb
<div class="row-fluid">
  <div class="switch-board-round">
    <ul class="clearfix">
      <li class="<%=active_action('events','easy_new')%>">
        <%=link_to easy_new_admin_events_path, :class => "tip-top", :rel => "tooltip", "data-original-title" => "Agendamento Fácil" do%>	
          <span class="icon-magic"></span>
        <%end%>        
      </li>
      <li class="<%=active_action('events','new')%>">
        <%=link_to new_admin_event_path, :class => "tip-top", :rel => "tooltip", "data-original-title" => "Agendamento Manual" do%>  
          <span class="icon-plus"></span>
        <%end%>
      </li>
      <li class="<%=active_action('events','index')%>">
        <%=link_to admin_events_path, :class => "tip-top", :rel => "tooltip", "data-original-title" => "Meus Agendamentos" do%>  
          <span class="icon-list"></span>
        <%end%>
      </li>
      <%if action_name == "show"%>
        <li>
        <%=link_to edit_admin_event_path(@event), :class => "tip-top", :rel => "tooltip", "data-original-title" => "Editar Agendamento" do%>  
          <span class="icon-edit"></span>
        <%end%>
      </li>
      <%end%>
   </ul>
 </div>
</div>

app/views/admin/events/_index.html.erb
<%=render "top_menu"%>

<header>
	<h2>Listar Agendamentos</h2>
</header>
<div id="main-content">
	<%=render "context_menu"%>
	<h4 class="sub">
		<span>
			Escolha o modo de visualização dos dados
		</span>
	</h4>
	<ul class="nav nav-pills">
		<li class="<%=active_action('events','calendar')%>">
			<%=link_to "Calendário", calendar_admin_events_path%>
		</li>
		<li class="<%=active_action('events','index')%>">
			<%=link_to "Lista", admin_events_path%>
		</li>		
	</ul>
	
	<%if action_name == "calendar"%>	
		<%=render "calendar_view"%>	
	<%else%>
		<%=render "list_view"%>
	<%end%>
</div>

app/views/admin/events/_index_events_list.html.erb
<div class="fc">
  <div class="fc-header" style="width:100%">
    <div class="fc-header-left">
      <span class="fc-btn fc-button-prev fc-corner-left fc-corner-right">
        <%=link_to :month => (@date.beginning_of_month-1).strftime("%Y-%m-01") do%>
          <i class="icon-chevron-left cal_prev"></i>
        <%end%>
        
      </span>
      <span class="fc-header-space"></span>
      <span class="fc-btn fc-button-next fc-corner-left fc-corner-right">
        <%=link_to :month => (@date.end_of_month+1).strftime("%Y-%m-01") do%>
          <i class="icon-chevron-right cal_next"></i>
        <%end%>
      </span>
    </div>
    <div class="fc-header-center">
      <span class="fc-header-title">
        <h2><%=l @date, :format => :month_year%></h2>
      </span>
      <span class="fc-btn fc-button-today fc-corner-left fc-corner-right fc-state-disabled">today</span>
    </div>
    <div class="fc-header-right"><span class="fc-btn fc-button-month fc-corner-left fc-state-active">month</span><span class="fc-btn fc-button-agendaWeek">week</span><span class="fc-btn fc-button-agendaDay fc-corner-right">day</span></div>
                  
                  
  </div>
  <div id="event-content">

    <%= calendar_for @events, :year => @date.year, :month => @date.month, :html => {:class => "calendar"} do |calendar| %>
      <%= calendar.head('Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado') %>
      <% calendar.day(:day_method => :start_at) do |date, events| %>
        <div class="day_number" data-date="<%=date%>">
          <%= date.day %>
          <%=link_to image_tag("ico/add.png"), "##{date.strftime("%d-%m-%Y")}"%>
        </div>

        <% for event in events %>
          <%#= render event %>
        <% end %>

      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/events/_top_menu.html.erb
<%=content_for :top_menu do%>
	<%if action_name != "index" || params[:professional].present?%>
		<%=link_to admin_events_path, :class => "item" do%>
		<span class="item-icon">
			<i class="icon-list"></i>
		</span>
		<span class="item-label">Listar Agendamentos</span>								
		<%end%>
	<%end%>	
	<%if action_name != "easy_new"%>
		<%=link_to easy_new_admin_events_path, :class => "item" do%>
		<span class="item-icon">
			<i class="icon-magic"></i>
		</span>
		<span class="item-label">Agendamento Fácil</span>								
		<%end%>
	<%end%>
	<%if action_name != "new"%>
		<%=link_to new_admin_event_path, :class => "item" do%>
		<span class="item-icon">
			<i class="icon-plus"></i>
		</span>
		<span class="item-label">Agendamento Manual</span>								
		<%end%>
	<%end%>	
<%end%>

app/views/admin/events/calendar.html.erb
<%=render "index"%>

app/views/admin/events/create_error.js.erb
window.location.reload();

app/views/admin/events/easy_create.js.erb
window.location = "<%=admin_event_path(@event)%>"

app/views/admin/events/edit.html.erb
<%=render "top_menu"%>
<%=render "/admin/clients/modal_form"%>

<header>
	<h2>
		Alteração de Agendamento
	</h2>
</header>

<div id="main-content">
	<%=render "context_menu"%>
	<div class="row-fluid">
		<div class="widget span12">
			<div class="widget-header">
				<span class="title">
					Alterando um agendamento
				</span>
			</div>
			<div class="widget-content form-container">
				<div class="control-group">
					<%=render "/events/form"%>				
				</div>				
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	/*$("#new_client").on('hidden',function(){
		console.log("substituindo");
		$("#new_client").replaceWith("escape_javascript(render '/admin/clients/modal_form')");
	});*/
</script>


  

app/views/admin/events/search.html.erb
<%=render "top_nav"%>

<div class="row-fluid">
	<div class="span12">
		<h2 class="heading">Agendamentos</h2>
		<table class="table table-bordered table-striped table_vam" id="dt_gal">
			<thead>
				<tr>
					<th>Cliente</th>
					<th>Serviço</th>
					<th>Funcionário</th>
					<th>Data</th>
					<th>Duração</th>
					<th>Ação</th>
				</tr>
			</thead>
			<tbody>

				<%@events.each do |event|%>
				<tr>					
					<td>
						<%=event.client.name if event.client%>
					</td>
					<td>
						<%=event.service.name if event.service%>
					</td>
					<td>
						<%=event.professional.name if event.professional%>
					</td>
					<td>
						<%=event.start_at.strftime("%d de %B às %H:%M")%>
					</td>
					<td>
						<%=distance_of_time_in_words(event.start_at,event.end_at)%>
					</td>
					<td>
						<%=link_to [:admin,event], 
						"data-method-type" => :delete, 
						:class => "btn btn-mini pull-right btn-danger confirmable",
						"data-message" => "Deseja realmente cancelar este agendamento?" do%>
						<i class="icon-trash"></i>
						Cancelar
						<%end%>
					</td>
				</tr>
				<%end%>
			</tbody>
		</table>

	</div>
</div>

app/views/admin/events/show.html.erb
<%=render "top_menu"%>

<header>
	<h2>
		Detalhes do agendamento
	</h2>
</header>

<div id="main-content">
	<%=render "context_menu"%>
	<div class="row-fluid">
		<div class="form-horizontal widget">
			<div class="widget-header">
				<span class="title">
					Detalhes do Agendamento
				</span>
				<div class="toolbar">
					<%=link_to "Remarcar Evento", edit_admin_event_path(@event), :class => "btn btn-mini" %>
				</div>
			</div>
			<div class="widget-content table-container">
				<table class="table table-detail-view">
					<tbody>
						<tr>
							<th>Código</th>
							<td><%=@event.id%></td>
						</tr>
						<tr>
							<th>Salão</th>
							<td><%=link_to @event.salon.name, [:admin,@event.salon]%></td>
						</tr>
						<tr>
							<th>Cliente</th>
							<td><%=link_to @event.client.name, [:admin,@event.client] if @event.client%></td>
						</tr>
						<tr>
							<th>Serviço</th>
							<td><%=link_to @event.service.name, [:admin, @event.service] if @event.service%></td>
						</tr>
						<tr>
							<th>Início</th>
							<td><%=@event.start_at.strftime("%d de %B às %H:%Mh")%></td>
						</tr>
						<tr>
							<th>Fim</th>
							<td><%=@event.end_at.strftime("%d de %B às %H:%Mh") if @event.salon%></td>
						</tr>
						<tr>
							<th>Duração</th>
							<td><%=distance_of_time_in_words(@event.start_at,@event.end_at)%></td>
						</tr>
						<tr>
							<th>Situação</th>
							<td>
								<span class="badge badge-<%=event_type(@event)%>">
                                                <%=@event.status%>
                                            </span>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>		

app/views/admin/events/show.js.erb
var modal = $("#ajax-modal");
var modal_content = "<%=escape_javascript(render(:partial => 'show', :layout => false))%>";
modal.html(modal_content);
modal.modal();