config/routes.rb
Smartsalon::Application.routes.draw do

  get "client_services/index"

  get "client_services/new"

  get "dashboard/index"

  get "dashboard" => "dashboard#index"

  post "favorites" => "favorites#create"

  delete "favorites/:id" => "favorites#destroy"

  resources :settings

  namespace :landing do
    root :to => "pages#index"
    get "pages/index"
    get "pages/about"
  end

  namespace :admin do    
    root :to => "dashboard#index"
    post "payments/notification" => "payments#notification", :as => "payment_notification"
    get 'dashboard' => "dashboard#index"
    
    resources :services do
      collection do
        get 'get_services'
        get 'search'
      end
      resources :client_services
    end      
    
    resources :events do      
      collection do
        get "easy/new" => "events#easy_new"
        post "easy/new" => "events#easy_create"
        get 'get_events'
        get 'search'
        get 'calendar'
      end
      member do
        post "edit" => "events#update"
      end
    end
    
    resources :professionals do
      collection do
        post "search_zipcode" => "professionals#search_zipcode"
      end
      put "update_password" => "professionals#update_password", :as => "update_password", :on => :member
      resources :working_times
      resources :professional_services
    end
    
    resources :salons do
      collection do
        post "search_zipcode" => "salons#search_zipcode"
      end
      post "payments/checkout" => "payments#checkout", :as => "payments_checkout"
      get "payments/:payment_id/receipt" => "payments#receipt", :as => "payments_receipt"
    end
    
    resources :clients do
      post "add/to/salon" => "clients#add_to_salon", :as => "add_to_salon"
      collection do
        get "search"
      end
      resources :client_services      
    end
    
    resources :client_services
  end

  devise_for :clients, :controllers =>
  {
    :registrations => "registrations"
  }

  devise_for :users, :controllers => 
  { 
    :registrations => "registrations" ,
    :sessions => "sessions"
  }

  devise_for :professionals, 
  :controllers => 
  { 
    :registrations => "registrations" ,
    :sessions => "admin/sessions"
  }

  resources :clients do
    resources :events
  end

  resources :salons do
    get 'page/:page', :action => :index, :on => :collection
    post "events/:id/edit" => "events#update"
    post "events/new" => "events#create"
    resources :events
  end

  resources :events

  resources :users

  root :to => "dashboard#index"

end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Instanapp - Salão</title>
	<%= stylesheet_link_tag    "application-admin", :media => "all" %>
	<%= javascript_include_tag "application-admin" %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	<div class="modal hide fade" id="confirmation-modal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>Confirmação</h3>
		</div>
		<div class="modal-body">
			<p></p>
		</div>
		<div style="display:none" class="link" data-destination="">
		</div>
		<div class="modal-footer">
			<a href="#" class="btn" data-dismiss = "modal">Cancelar</a>
			<a class="btn btn-primary" id="confirm-btn">Confirmar</a>
		</div>
	</div>
	<div id="ajax-modal" class="modal hide fade" tabindex="-1"></div>
	<div class="modal hide" id="loading-modal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>Carregando...</h3>
		</div>
		<div class="modal-body">
			<p>
				Processando, por favor aguarde...								
			</p>
			<br />
			<%=image_tag "/assets/ajax_loader.gif"%>
		</div>
		<div style="display:none" class="link" data-destination="">
		</div>		
	</div>		
	<aside id="aside_sidebar" class="collapse">
		<div class="logo">
			<a href="index.html"></a>
		</div>
		<ul id="sidebar_menu" class="navbar nav nav-list sidebar_box">
			<li class="accordion-group <%=active_class('dashboard')%>">
				<%=link_to admin_dashboard_path do%>	
				<%=image_tag "/assets/menu_icons/dashboard.png"%>								
				Dashboard
				<%end%>				
			</li>
			<li class="accordion-group <%=active_class('events')%>">
				<%=link_to admin_events_path do%>	
				<%=image_tag "/assets/menu_icons/calendar.png"%>								
				Agenda					
				<%end%>									
			</li>
			<li class="accordion-group <%=active_class('services')%>">
				<%=link_to admin_services_path do%>	
				<%=image_tag "/assets/menu_icons/tools.png"%>								
				Serviços					
				<%end%>									
			</li>
			<li class="accordion-group <%=active_class('professionals')%>">
				<%=link_to admin_professionals_path do%>	
				<%=image_tag "/assets/menu_icons/profile.png"%>								
				Funcionários					
				<%end%>									
			</li>
			<li class="accordion-group <%=active_class('clients')%>">
				<%=link_to admin_clients_path do%>	
				<%=image_tag "/assets/menu_icons/users.png"%>								
				Clientes					
				<%end%>									
			</li>
			<li class="accordion-group <%=active_class('salons')%>">
				<%=link_to [:admin, @salon] do%>	
				<%=image_tag "/assets/menu_icons/settings.png"%>								
				Gerenciar Salão
				<%end%>									
			</li>

		</ul>
		<!-- End sidebar_box -->
	</aside>
	<div id="main">		
		<div class="container">				
			<div class="container_top" id="header">
				<div class="row-fluid ">
					<div id="dropdown-lists">
						<%=link_to :back, :class => "item" do%>
						<span class="item-icon">
							<i class="icon-arrow-left"></i>
						</span>
						<span class="item-label">Voltar</span>								
						<%end%>
						<%=yield(:top_menu)%>						
					</div>
					
					<div class="top_right">     
						<ul class="nav nav_menu">                
						</ul>
					</div> <!-- End top-right -->
				</div>
			</div>
			<div id="container2">
				<%= yield %>	
			</div>
		</div>
		<div id="footer">
			<p>
				© Bird Admin Template 2012
			</p>
			<span class="company_logo"><a href="http://www.pixelgrade.com"></a></span>
		</div>
	</div>
</body>
<script type="text/javascript">
function displayAllRailsNotification(){
	<% flash.each do |name, msg| %>			
		// ----------- Notification Settings ----------------//			
		text = "<%=escape_javascript(msg)%>";
		type = "<%= escape_javascript(name.to_s == 'notice' ? 'success' : 'error')%>";		
		$.pnotify({			
			text: text,
			type: type			
		});
		//---------------------------------------------------//		
	<%end%>					
	<%flash.discard%>	
}

function displayOneRailsNotification(msg,type){
	type = type == "notice" ? "success" : "error";
	$.pnotify({			
		text: msg,
		type: type			
	});	
}

jQuery(document).ready(function($) {
	var text;
	var type;
	$.pnotify.defaults.history = false;
	$.pnotify.defaults.delay = 4000; // 4 Seconds to fade out notification
	$.pnotify.defaults.title = false;
	$.pnotify.defaults.width = "30%";
	$.pnotify.defaults.sticker = false;
	displayAllRailsNotification();
	
	$(document).ajaxComplete(function(event, request) {
	    var msg = request.getResponseHeader('X-Message');
	    var type = request.getResponseHeader('X-Message-Type');
	    if (msg){
	    	displayOneRailsNotification(msg, type);
	    }
	    	

	});	
});

</script>

</html>